FROM	alpine:3.18.4

LABEL author="abouabra <abouabra@student.1337.ma>"
LABEL description="A content management system that will be used to create and manage the website"
LABEL version="0.1.0"
LABEL url="https://github.com/abouabra/inception"


RUN		apk update