version: '3'

services:
  nginx:
    image: inception:nginx
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - wordpress
      - redis
      - adminer
    ports:
      - 443:443
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  wordpress:
    image: inception:wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  mariadb:
    image: inception:mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  redis:
    image: inception:redis
    container_name: redis
    build: ./requirements/bonus/redis/
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  adminer:
    image: inception:adminer
    container_name: adminer
    build: ./requirements/bonus/adminer/
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      device: /home/abouabra/data/mariadb
      o: bind

  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: /home/abouabra/data/wordpress
      o: bind


networks:
  inception_net:
    driver: bridge