version: '3'

services:
  nginx:
    image: inception:nginx
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - wordpress
      - redis
      - adminer
      - portfolio
    ports:
      - 443:443
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  wordpress:
    image: inception:wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  mariadb:
    image: inception:mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  redis:
    image: inception:redis
    container_name: redis
    build: ./requirements/bonus/redis/
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  adminer:
    image: inception:adminer
    container_name: adminer
    build: ./requirements/bonus/adminer/
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception_net
    env_file:
      - .env
    restart: always

  portfolio:
      image: inception:portfolio
      container_name: portfolio
      build: ./requirements/bonus/portfolio/
      networks:
        - inception_net
      env_file:
        - .env
      restart: always

  netdata:
    image: inception:netdata
    container_name: netdata
    build: ./requirements/bonus/netdata
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
    ports:
      - 8080:19999
    restart: always
volumes:
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      device: /home/ayman/data/mariadb
      o: bind

  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: /home/ayman/data/wordpress
      o: bind


networks:
  inception_net:
    driver: bridge