version: '3'

services:
  nginx:
    image: inception:nginx
    container_name: nginx
    build: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_net
    restart: always

  wordpress:
    image: inception:wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_net
    restart: always
  mariadb:
    image: inception:mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_net
    restart: always

volumes:
    wordpress_volume:
        driver: local
        driver_opts:
            type: none
            device: /home/abouabra/data/wordpress/
            o: bind
    mariadb_volume:
      driver: local
      driver_opts:
          type: none
          device: /home/abouabra/data/mariadb/
          o: bind

networks:
  inception_net:
    driver: bridge